# Switches
set_property PACKAGE_PIN V17 [get_ports {s3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s3}]
set_property PACKAGE_PIN V16 [get_ports {s2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s2}]
set_property PACKAGE_PIN W16 [get_ports {s1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {s1}]
set_property PACKAGE_PIN W17 [get_ports {a7}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a7}]
set_property PACKAGE_PIN W15 [get_ports {a6}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a6}]
set_property PACKAGE_PIN V15 [get_ports {a5}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a5}]
set_property PACKAGE_PIN W14 [get_ports {a4}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a4}]
set_property PACKAGE_PIN W13 [get_ports {a3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a3}]
set_property PACKAGE_PIN V2 [get_ports {a2}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {a2}]
set_property PACKAGE_PIN T3 [get_ports {a1}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property PACKAGE_PIN T2 [get_ports {a0}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {a0}]
    
#LEDS
set_property PACKAGE_PIN U16 [get_ports {y}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {y}]